In [1]:
import pandas as pd

In [2]:
avg_nutrition_df = pd.read_csv('Average_Days_Nutrition.csv')
access_to_care_df = pd.read_csv('Cleaned_Access_to_Care.csv')
ages_df = pd.read_csv('Cleaned_Ages.csv')
blood_pressure_df = pd.read_csv('Cleaned_Blood_Pressure.csv')
blpr_chol_df = pd.read_csv('Cleaned_BLPR_CHOL.csv')
body_measures_df = pd.read_csv('Cleaned_Body_Measures.csv')
demographics_df = pd.read_csv('Cleaned_Demographics.csv')
diet_behavior_df = pd.read_csv('Cleaned_Diet_Behavior.csv')
disabilities_df = pd.read_csv('Cleaned_Disabilities.csv')
health_insurance_df = pd.read_csv('Cleaned_Health_Insurance.csv')
household_smoking_df = pd.read_csv('Cleaned_Household_Smoking.csv')
income_df = pd.read_csv('Cleaned_Income.csv')
medical_conditions_df = pd.read_csv('Cleaned_Medical_Conditions.csv')
mental_health_df = pd.read_csv('Cleaned_Mental_Health.csv')
physical_activities_df = pd.read_csv('Cleaned_Physical_Activities.csv')
sleep_df = pd.read_csv('Cleaned_Sleep.csv')
smoking_df = pd.read_csv('Cleaned_Smoking.csv')
weight_history_df = pd.read_csv('Cleaned_Weight_History.csv')
target_df = pd.read_csv('Target.csv')
food_location_df = pd.read_csv('Where_You_Get_Your_Food.csv')

In [3]:
print (str(avg_nutrition_df.shape)) 
print (str(access_to_care_df.shape))
print (str(ages_df.shape))
print (str(blood_pressure_df.shape))
print (str(blpr_chol_df.shape))
print (str(body_measures_df.shape))
print (str(demographics_df.shape))
print (str(diet_behavior_df.shape))
print (str(disabilities_df.shape))
print (str(health_insurance_df.shape))
print (str(household_smoking_df.shape))
print (str(income_df.shape))
print (str(medical_conditions_df.shape))
print (str(mental_health_df.shape))
print (str(physical_activities_df.shape))
print (str(sleep_df.shape))
print (str(smoking_df.shape))
print (str(weight_history_df.shape))
print (str(target_df.shape))
print (str(food_location_df.shape))

(5735, 69)
(5992, 12)
(5992, 3)
(5735, 7)
(5992, 5)
(5735, 7)
(5992, 59)
(5992, 13)
(5992, 3)
(5992, 3)
(5992, 8)
(5992, 11)
(5992, 5)
(5735, 11)
(5992, 25)
(5992, 12)
(5992, 5)
(5735, 11)
(5735, 3)
(5992, 6)

In [5]:
master_df = pd.merge(avg_nutrition_df, access_to_care_df, on="SEQN")
master_df = pd.merge(master_df, ages_df, on="SEQN")
master_df = pd.merge(master_df, blood_pressure_df, on="SEQN")
master_df = pd.merge(master_df, blpr_chol_df, on="SEQN")
master_df = pd.merge(master_df, body_measures_df, on="SEQN")
master_df = pd.merge(master_df, demographics_df, on="SEQN")
master_df = pd.merge(master_df, diet_behavior_df, on="SEQN")
master_df = pd.merge(master_df, disabilities_df, on="SEQN")
master_df = pd.merge(master_df, health_insurance_df, on="SEQN")
master_df = pd.merge(master_df, household_smoking_df, on="SEQN")
master_df = pd.merge(master_df, income_df, on="SEQN")
master_df = pd.merge(master_df, medical_conditions_df, on="SEQN")
master_df = pd.merge(master_df, mental_health_df, on="SEQN")
master_df = pd.merge(master_df, physical_activities_df, on="SEQN")
master_df = pd.merge(master_df, sleep_df, on="SEQN")
master_df = pd.merge(master_df, smoking_df, on="SEQN")
master_df = pd.merge(master_df, weight_history_df, on="SEQN")
master_df = pd.merge(master_df, target_df, on="SEQN")
master_df = pd.merge(master_df, food_location_df, on="SEQN")

In [6]:
print ('Master DF Shape: ' + str(master_df.shape))
master_df.head()

Master DF Shape: (5735, 259)

,Unnamed: 0_x,SEQN,DR3TKCAL,DR3TPROT,DR3TCARB,DR3TSUGR,DR3TFIBE,DR3TTFAT,DR3TSFAT,DR3TMFAT,...,WHQ225_5.0,WHQ030_2.0,WHQ030_3.0,Unnamed: 0_x,Target,Unnamed: 0_y,CBD071,CBD111,CBD121,CBD131
0,0,83732.0,2262.5,104.815,237.465,80.355,19.75,100.415,31.9250,37.1625,...,0,0,1,0,1.0,0,300.0,0.0,125.0,0.0
1,1,83733.0,3467.5,114.110,290.210,107.680,9.75,116.230,29.3455,40.0685,...,1,0,0,1,3.0,1,200.0,50.0,40.0,0.0
2,2,83734.0,2205.0,105.140,249.350,78.690,26.25,91.055,31.4755,29.4090,...,0,0,1,2,1.0,2,400.0,0.0,0.0,0.0
3,3,83735.0,1340.0,70.380,157.990,54.770,14.00,49.230,17.5930,18.3270,...,0,0,0,3,2.0,3,300.0,250.0,50.0,0.0
4,4,83736.0,853.0,25.295,111.065,72.735,2.55,35.255,13.2585,13.1785,...,1,1,0,4,3.0,4,300.0,0.0,200.0,0.0

In [7]:
master_df = master_df.drop(['SEQN', 'Unnamed: 0_x', 'Unnamed: 0_y', 'Age_x', 'Age_y'], axis = 1)

In [8]:
print (str(master_df.shape[0]) + ' rows')
print (' ' + str(master_df.shape[1]) + ' columns')
master_df.head()

5735 rows
 234 columns

,DR3TKCAL,DR3TPROT,DR3TCARB,DR3TSUGR,DR3TFIBE,DR3TTFAT,DR3TSFAT,DR3TMFAT,DR3TPFAT,DR3TCHOL,...,WHQ225_3.0,WHQ225_4.0,WHQ225_5.0,WHQ030_2.0,WHQ030_3.0,Target,CBD071,CBD111,CBD121,CBD131
0,2262.5,104.815,237.465,80.355,19.75,100.415,31.9250,37.1625,22.6705,386.5,...,0,0,0,0,1,1.0,300.0,0.0,125.0,0.0
1,3467.5,114.110,290.210,107.680,9.75,116.230,29.3455,40.0685,33.1180,590.0,...,0,0,1,0,0,3.0,200.0,50.0,40.0,0.0
2,2205.0,105.140,249.350,78.690,26.25,91.055,31.4755,29.4090,21.5130,416.0,...,0,0,0,0,1,1.0,400.0,0.0,0.0,0.0
3,1340.0,70.380,157.990,54.770,14.00,49.230,17.5930,18.3270,9.5880,138.0,...,0,0,0,0,0,2.0,300.0,250.0,50.0,0.0
4,853.0,25.295,111.065,72.735,2.55,35.255,13.2585,13.1785,4.9155,138.5,...,0,0,1,1,0,3.0,300.0,0.0,200.0,0.0

In [9]:
cols = master_df.columns.tolist()
cols

['DR3TKCAL',
 'DR3TPROT',
 'DR3TCARB',
 'DR3TSUGR',
 'DR3TFIBE',
 'DR3TTFAT',
 'DR3TSFAT',
 'DR3TMFAT',
 'DR3TPFAT',
 'DR3TCHOL',
 'DR3TATOC',
 'DR3TATOA',
 'DR3TRET',
 'DR3TVARA',
 'DR3TACAR',
 'DR3TBCAR',
 'DR3TCRYP',
 'DR3TLYCO',
 'DR3TLZ',
 'DR3TVB1',
 'DR3TVB2',
 'DR3TNIAC',
 'DR3TVB6',
 'DR3TFOLA',
 'DR3TFA',
 'DR3TFF',
 'DR3TFDFE',
 'DR3TCHL',
 'DR3TVB12',
 'DR3TB12A',
 'DR3TVC',
 'DR3TVD',
 'DR3TVK',
 'DR3TCALC',
 'DR3TPHOS',
 'DR3TMAGN',
 'DR3TIRON',
 'DR3TZINC',
 'DR3TCOPP',
 'DR3TSODI',
 'DR3TPOTA',
 'DR3TSELE',
 'DR3TCAFF',
 'DR3TTHEO',
 'DR3TALCO',
 'DR3TMOIS',
 'DR3TS040',
 'DR3TS060',
 'DR3TS080',
 'DR3TS100',
 'DR3TS120',
 'DR3TS140',
 'DR3TS160',
 'DR3TS180',
 'DR3TM161',
 'DR3TM181',
 'DR3TM201',
 'DR3TM221',
 'DR3TP182',
 'DR3TP183',
 'DR3TP184',
 'DR3TP204',
 'DR3TP205',
 'DR3TP225',
 'DR3TP226',
 'DR3_320Z',
 'HUQ020_2.0',
 'HUQ020_3.0',
 'HUQ051_1.0',
 'HUQ051_2.0',
 'HUQ051_3.0',
 'HUQ051_4.0',
 'HUQ051_5.0',
 'HUQ051_6.0',
 'HUQ051_7.0',
 'HUQ051_8.0',
 'Heart Rate',
 'Systolic BP',
 'Diastolic BP',
 'Irregular Pulse',
 'BPQ020_1.0',
 'BPQ030_1.0',
 'BPQ080_1.0',
 'Weight (kg)',
 'Standing Height (cm)',
 'BMI',
 'Waist Circumference (cm)',
 'Age',
 'DMDHRAGE',
 'Sex_Female',
 'RIDRETH3_2.0',
 'RIDRETH3_3.0',
 'RIDRETH3_4.0',
 'RIDRETH3_6.0',
 'RIDRETH3_7.0',
 'DMQMILIZ_2.0',
 'DMDBORN4_2.0',
 'DMDCITZN_2.0',
 'SIALANG_2.0',
 'DMDHHSIZ_2.0',
 'DMDHHSIZ_3.0',
 'DMDHHSIZ_4.0',
 'DMDHHSIZ_5.0',
 'DMDHHSIZ_6.0',
 'DMDHHSIZ_7.0',
 'DMDFMSIZ_2.0',
 'DMDFMSIZ_3.0',
 'DMDFMSIZ_4.0',
 'DMDFMSIZ_5.0',
 'DMDFMSIZ_6.0',
 'DMDFMSIZ_7.0',
 'DMDHHSZA_1.0',
 'DMDHHSZA_2.0',
 'DMDHHSZA_3.0',
 'DMDHHSZB_1.0',
 'DMDHHSZB_2.0',
 'DMDHHSZB_3.0',
 'DMDHHSZB_4.0',
 'DMDHHSZE_1.0',
 'DMDHHSZE_2.0',
 'DMDHHSZE_3.0',
 'DMDHRGND_2.0',
 'DMDHREDU_2.0',
 'DMDHREDU_3.0',
 'DMDHREDU_4.0',
 'DMDHREDU_5.0',
 'DMDHRMAR_2.0',
 'DMDHRMAR_3.0',
 'DMDHRMAR_4.0',
 'DMDHRMAR_5.0',
 'DMDHRMAR_6.0',
 'INDFMIN2_2.0',
 'INDFMIN2_3.0',
 'INDFMIN2_4.0',
 'INDFMIN2_5.0',
 'INDFMIN2_6.0',
 'INDFMIN2_7.0',
 'INDFMIN2_8.0',
 'INDFMIN2_9.0',
 'INDFMIN2_10.0',
 'INDFMIN2_12.0',
 'INDFMIN2_13.0',
 'INDFMIN2_14.0',
 'INDFMIN2_15.0',
 'DBD895',
 'DBD905',
 'DBD910',
 'DBQ700_2.0',
 'DBQ700_3.0',
 'DBQ700_4.0',
 'DBQ700_5.0',
 'DBQ197_1.0',
 'DBQ197_2.0',
 'DBQ197_3.0',
 'DBQ197_4.0',
 'DLQ050_1.0',
 'HIQ011_1.0',
 'SMD460_1.0',
 'SMD460_2.0',
 'SMD460_3.0',
 'SMD470_1.0',
 'SMD470_2.0',
 'SMD470_3.0',
 'INQ132_1.0',
 'INQ320_2.0',
 'INQ320_3.0',
 'INQ320_4.0',
 'INQ320_5.0',
 'INQ320_6.0',
 'INQ320_7.0',
 'INQ320_8.0',
 'INQ320_9.0',
 'MCQ010_1.0',
 'MCQ080_1.0',
 'MCQ220_1.0',
 'DPQ030_1.0',
 'DPQ030_2.0',
 'DPQ030_3.0',
 'DPQ040_1.0',
 'DPQ040_2.0',
 'DPQ040_3.0',
 'DPQ050_1.0',
 'DPQ050_2.0',
 'DPQ050_3.0',
 'PAQ640',
 'PAD645',
 'PAQ655',
 'PAD660',
 'PAQ670',
 'PAD675',
 'PAD680',
 'PAQ635_1.0',
 'PAQ635_95.0',
 'PAQ650_1.0',
 'PAQ665_1.0',
 'PAQ710_1.0',
 'PAQ710_2.0',
 'PAQ710_3.0',
 'PAQ710_4.0',
 'PAQ710_5.0',
 'PAQ710_8.0',
 'PAQ715_1.0',
 'PAQ715_2.0',
 'PAQ715_3.0',
 'PAQ715_4.0',
 'PAQ715_5.0',
 'PAQ715_8.0',
 'SLQ310',
 'SLD012',
 'SLQ030_1.0',
 'SLQ030_2.0',
 'SLQ030_3.0',
 'SLQ030_9.0',
 'SLQ120_1.0',
 'SLQ120_2.0',
 'SLQ120_3.0',
 'SLQ120_4.0',
 'SMQ040_2.0',
 'SMQ040_3.0',
 'SMQ020_1.0',
 'WHD050',
 'WHD140',
 'WHQ150',
 'WHQ225_2.0',
 'WHQ225_3.0',
 'WHQ225_4.0',
 'WHQ225_5.0',
 'WHQ030_2.0',
 'WHQ030_3.0',
 'Target',
 'CBD071',
 'CBD111',
 'CBD121',
 'CBD131']

In [10]:
# Drop all row that I don't have nutrition data for
master_df = master_df[master_df['DR3TKCAL'] != -1]

In [11]:
print (str(master_df.shape[0]) + ' rows')
print (' ' + str(master_df.shape[1]) + ' columns')
master_df.head()

5266 rows
 234 columns

,DR3TKCAL,DR3TPROT,DR3TCARB,DR3TSUGR,DR3TFIBE,DR3TTFAT,DR3TSFAT,DR3TMFAT,DR3TPFAT,DR3TCHOL,...,WHQ225_3.0,WHQ225_4.0,WHQ225_5.0,WHQ030_2.0,WHQ030_3.0,Target,CBD071,CBD111,CBD121,CBD131
0,2262.5,104.815,237.465,80.355,19.75,100.415,31.9250,37.1625,22.6705,386.5,...,0,0,0,0,1,1.0,300.0,0.0,125.0,0.0
1,3467.5,114.110,290.210,107.680,9.75,116.230,29.3455,40.0685,33.1180,590.0,...,0,0,1,0,0,3.0,200.0,50.0,40.0,0.0
2,2205.0,105.140,249.350,78.690,26.25,91.055,31.4755,29.4090,21.5130,416.0,...,0,0,0,0,1,1.0,400.0,0.0,0.0,0.0
3,1340.0,70.380,157.990,54.770,14.00,49.230,17.5930,18.3270,9.5880,138.0,...,0,0,0,0,0,2.0,300.0,250.0,50.0,0.0
4,853.0,25.295,111.065,72.735,2.55,35.255,13.2585,13.1785,4.9155,138.5,...,0,0,1,1,0,3.0,300.0,0.0,200.0,0.0

In [12]:
# Check for NaN's
master_df.isnull().values.any()

False

In [13]:
master_df.head()

,DR3TKCAL,DR3TPROT,DR3TCARB,DR3TSUGR,DR3TFIBE,DR3TTFAT,DR3TSFAT,DR3TMFAT,DR3TPFAT,DR3TCHOL,...,WHQ225_3.0,WHQ225_4.0,WHQ225_5.0,WHQ030_2.0,WHQ030_3.0,Target,CBD071,CBD111,CBD121,CBD131
0,2262.5,104.815,237.465,80.355,19.75,100.415,31.9250,37.1625,22.6705,386.5,...,0,0,0,0,1,1.0,300.0,0.0,125.0,0.0
1,3467.5,114.110,290.210,107.680,9.75,116.230,29.3455,40.0685,33.1180,590.0,...,0,0,1,0,0,3.0,200.0,50.0,40.0,0.0
2,2205.0,105.140,249.350,78.690,26.25,91.055,31.4755,29.4090,21.5130,416.0,...,0,0,0,0,1,1.0,400.0,0.0,0.0,0.0
3,1340.0,70.380,157.990,54.770,14.00,49.230,17.5930,18.3270,9.5880,138.0,...,0,0,0,0,0,2.0,300.0,250.0,50.0,0.0
4,853.0,25.295,111.065,72.735,2.55,35.255,13.2585,13.1785,4.9155,138.5,...,0,0,1,1,0,3.0,300.0,0.0,200.0,0.0

# Cosmetics

* Rename Columns
* Reorder columns
    * Mainly have target and age and weight first

In [14]:
master_df = master_df.rename(columns={'DR3TKCAL': 'Calories', 
                                      'DR3TPROT': 'Protein (gm)',
                                      'DR3TCARB': 'Carbohydrates (gm)', 
                                      'DR3TSUGR': 'Sugars (gm)',
                                      'DR3TFIBE': 'Dietary Fiber (gm)', 
                                      'DR3TTFAT': 'Total Fat (gm)',
                                      'DR3TSFAT': 'Saturated Fatty Acids (gm)', 
                                      'DR3TMFAT': 'Monosaturated Fatty Acids (gm)',
                                      'DR3TPFAT': 'Polyunsaturated Fatty Acids (gm)', 
                                      'DR3TCHOL': 'Cholesterol (mg)',
                                      'DR3TATOC': 'Vit E as alpha-tocopherol (mg)', 
                                      'DR3TATOA': 'Alpha-tocopherol Added (mg)',
                                      'DR3TRET': 'Retinol (mcg)', 
                                      'DR3TVARA': 'Vit A, RAE (mcg)',
                                      'DR3TACAR': 'Alpha-carotene (mcg)', 
                                      'DR3TBCAR': 'Beta-carotene (mcg)'
                                     })

In [15]:
new_order = ['Target', 'Age', 'Sex_Female', 'Weight (kg)', 'Standing Height (cm)', 'BMI',
             'Waist Circumference (cm)','Calories',
 'Protein (gm)',
 'Carbohydrates (gm)',
 'Sugars (gm)',
 'Dietary Fiber (gm)',
 'Total Fat (gm)',
 'Saturated Fatty Acids (gm)',
 'Monosaturated Fatty Acids (gm)',
 'Polyunsaturated Fatty Acids (gm)',
 'Cholesterol (mg)',
 'Vit E as alpha-tocopherol (mg)',
 'Alpha-tocopherol Added (mg)',
 'Retinol (mcg)',
 'Vit A, RAE (mcg)',
 'Alpha-carotene (mcg)',
 'Beta-carotene (mcg)',
 'DR3TCRYP',
 'DR3TLYCO',
 'DR3TLZ',
 'DR3TVB1',
 'DR3TVB2',
 'DR3TNIAC',
 'DR3TVB6',
 'DR3TFOLA',
 'DR3TFA',
 'DR3TFF',
 'DR3TFDFE',
 'DR3TCHL',
 'DR3TVB12',
 'DR3TB12A',
 'DR3TVC',
 'DR3TVD',
 'DR3TVK',
 'DR3TCALC',
 'DR3TPHOS',
 'DR3TMAGN',
 'DR3TIRON',
 'DR3TZINC',
 'DR3TCOPP',
 'DR3TSODI',
 'DR3TPOTA',
 'DR3TSELE',
 'DR3TCAFF',
 'DR3TTHEO',
 'DR3TALCO',
 'DR3TMOIS',
 'DR3TS040',
 'DR3TS060',
 'DR3TS080',
 'DR3TS100',
 'DR3TS120',
 'DR3TS140',
 'DR3TS160',
 'DR3TS180',
 'DR3TM161',
 'DR3TM181',
 'DR3TM201',
 'DR3TM221',
 'DR3TP182',
 'DR3TP183',
 'DR3TP184',
 'DR3TP204',
 'DR3TP205',
 'DR3TP225',
 'DR3TP226',
 'DR3_320Z',
 'HUQ020_2.0',
 'HUQ020_3.0',
 'HUQ051_1.0',
 'HUQ051_2.0',
 'HUQ051_3.0',
 'HUQ051_4.0',
 'HUQ051_5.0',
 'HUQ051_6.0',
 'HUQ051_7.0',
 'HUQ051_8.0',
 'Heart Rate',
 'Systolic BP',
 'Diastolic BP',
 'Irregular Pulse',
 'BPQ020_1.0',
 'BPQ030_1.0',
 'BPQ080_1.0',
 'DMDHRAGE',
 'RIDRETH3_2.0',
 'RIDRETH3_3.0',
 'RIDRETH3_4.0',
 'RIDRETH3_6.0',
 'RIDRETH3_7.0',
 'DMQMILIZ_2.0',
 'DMDBORN4_2.0',
 'DMDCITZN_2.0',
 'SIALANG_2.0',
 'DMDHHSIZ_2.0',
 'DMDHHSIZ_3.0',
 'DMDHHSIZ_4.0',
 'DMDHHSIZ_5.0',
 'DMDHHSIZ_6.0',
 'DMDHHSIZ_7.0',
 'DMDFMSIZ_2.0',
 'DMDFMSIZ_3.0',
 'DMDFMSIZ_4.0',
 'DMDFMSIZ_5.0',
 'DMDFMSIZ_6.0',
 'DMDFMSIZ_7.0',
 'DMDHHSZA_1.0',
 'DMDHHSZA_2.0',
 'DMDHHSZA_3.0',
 'DMDHHSZB_1.0',
 'DMDHHSZB_2.0',
 'DMDHHSZB_3.0',
 'DMDHHSZB_4.0',
 'DMDHHSZE_1.0',
 'DMDHHSZE_2.0',
 'DMDHHSZE_3.0',
 'DMDHRGND_2.0',
 'DMDHREDU_2.0',
 'DMDHREDU_3.0',
 'DMDHREDU_4.0',
 'DMDHREDU_5.0',
 'DMDHRMAR_2.0',
 'DMDHRMAR_3.0',
 'DMDHRMAR_4.0',
 'DMDHRMAR_5.0',
 'DMDHRMAR_6.0',
 'INDFMIN2_2.0',
 'INDFMIN2_3.0',
 'INDFMIN2_4.0',
 'INDFMIN2_5.0',
 'INDFMIN2_6.0',
 'INDFMIN2_7.0',
 'INDFMIN2_8.0',
 'INDFMIN2_9.0',
 'INDFMIN2_10.0',
 'INDFMIN2_12.0',
 'INDFMIN2_13.0',
 'INDFMIN2_14.0',
 'INDFMIN2_15.0',
 'DBD895',
 'DBD905',
 'DBD910',
 'DBQ700_2.0',
 'DBQ700_3.0',
 'DBQ700_4.0',
 'DBQ700_5.0',
 'DBQ197_1.0',
 'DBQ197_2.0',
 'DBQ197_3.0',
 'DBQ197_4.0',
 'DLQ050_1.0',
 'HIQ011_1.0',
 'SMD460_1.0',
 'SMD460_2.0',
 'SMD460_3.0',
 'SMD470_1.0',
 'SMD470_2.0',
 'SMD470_3.0',
 'INQ132_1.0',
 'INQ320_2.0',
 'INQ320_3.0',
 'INQ320_4.0',
 'INQ320_5.0',
 'INQ320_6.0',
 'INQ320_7.0',
 'INQ320_8.0',
 'INQ320_9.0',
 'MCQ010_1.0',
 'MCQ080_1.0',
 'MCQ220_1.0',
 'DPQ030_1.0',
 'DPQ030_2.0',
 'DPQ030_3.0',
 'DPQ040_1.0',
 'DPQ040_2.0',
 'DPQ040_3.0',
 'DPQ050_1.0',
 'DPQ050_2.0',
 'DPQ050_3.0',
 'PAQ640',
 'PAD645',
 'PAQ655',
 'PAD660',
 'PAQ670',
 'PAD675',
 'PAD680',
 'PAQ635_1.0',
 'PAQ635_95.0',
 'PAQ650_1.0',
 'PAQ665_1.0',
 'PAQ710_1.0',
 'PAQ710_2.0',
 'PAQ710_3.0',
 'PAQ710_4.0',
 'PAQ710_5.0',
 'PAQ710_8.0',
 'PAQ715_1.0',
 'PAQ715_2.0',
 'PAQ715_3.0',
 'PAQ715_4.0',
 'PAQ715_5.0',
 'PAQ715_8.0',
 'SLQ310',
 'SLD012',
 'SLQ030_1.0',
 'SLQ030_2.0',
 'SLQ030_3.0',
 'SLQ030_9.0',
 'SLQ120_1.0',
 'SLQ120_2.0',
 'SLQ120_3.0',
 'SLQ120_4.0',
 'SMQ040_2.0',
 'SMQ040_3.0',
 'SMQ020_1.0',
 'WHD050',
 'WHD140',
 'WHQ150',
 'WHQ225_2.0',
 'WHQ225_3.0',
 'WHQ225_4.0',
 'WHQ225_5.0',
 'WHQ030_2.0',
 'WHQ030_3.0',
 'CBD071',
 'CBD111',
 'CBD121',
 'CBD131']

In [16]:
new_order

['Target',
 'Age',
 'Sex_Female',
 'Weight (kg)',
 'Standing Height (cm)',
 'BMI',
 'Waist Circumference (cm)',
 'Calories',
 'Protein (gm)',
 'Carbohydrates (gm)',
 'Sugars (gm)',
 'Dietary Fiber (gm)',
 'Total Fat (gm)',
 'Saturated Fatty Acids (gm)',
 'Monosaturated Fatty Acids (gm)',
 'Polyunsaturated Fatty Acids (gm)',
 'Cholesterol (mg)',
 'Vit E as alpha-tocopherol (mg)',
 'Alpha-tocopherol Added (mg)',
 'Retinol (mcg)',
 'Vit A, RAE (mcg)',
 'Alpha-carotene (mcg)',
 'Beta-carotene (mcg)',
 'DR3TCRYP',
 'DR3TLYCO',
 'DR3TLZ',
 'DR3TVB1',
 'DR3TVB2',
 'DR3TNIAC',
 'DR3TVB6',
 'DR3TFOLA',
 'DR3TFA',
 'DR3TFF',
 'DR3TFDFE',
 'DR3TCHL',
 'DR3TVB12',
 'DR3TB12A',
 'DR3TVC',
 'DR3TVD',
 'DR3TVK',
 'DR3TCALC',
 'DR3TPHOS',
 'DR3TMAGN',
 'DR3TIRON',
 'DR3TZINC',
 'DR3TCOPP',
 'DR3TSODI',
 'DR3TPOTA',
 'DR3TSELE',
 'DR3TCAFF',
 'DR3TTHEO',
 'DR3TALCO',
 'DR3TMOIS',
 'DR3TS040',
 'DR3TS060',
 'DR3TS080',
 'DR3TS100',
 'DR3TS120',
 'DR3TS140',
 'DR3TS160',
 'DR3TS180',
 'DR3TM161',
 'DR3TM181',
 'DR3TM201',
 'DR3TM221',
 'DR3TP182',
 'DR3TP183',
 'DR3TP184',
 'DR3TP204',
 'DR3TP205',
 'DR3TP225',
 'DR3TP226',
 'DR3_320Z',
 'HUQ020_2.0',
 'HUQ020_3.0',
 'HUQ051_1.0',
 'HUQ051_2.0',
 'HUQ051_3.0',
 'HUQ051_4.0',
 'HUQ051_5.0',
 'HUQ051_6.0',
 'HUQ051_7.0',
 'HUQ051_8.0',
 'Heart Rate',
 'Systolic BP',
 'Diastolic BP',
 'Irregular Pulse',
 'BPQ020_1.0',
 'BPQ030_1.0',
 'BPQ080_1.0',
 'DMDHRAGE',
 'RIDRETH3_2.0',
 'RIDRETH3_3.0',
 'RIDRETH3_4.0',
 'RIDRETH3_6.0',
 'RIDRETH3_7.0',
 'DMQMILIZ_2.0',
 'DMDBORN4_2.0',
 'DMDCITZN_2.0',
 'SIALANG_2.0',
 'DMDHHSIZ_2.0',
 'DMDHHSIZ_3.0',
 'DMDHHSIZ_4.0',
 'DMDHHSIZ_5.0',
 'DMDHHSIZ_6.0',
 'DMDHHSIZ_7.0',
 'DMDFMSIZ_2.0',
 'DMDFMSIZ_3.0',
 'DMDFMSIZ_4.0',
 'DMDFMSIZ_5.0',
 'DMDFMSIZ_6.0',
 'DMDFMSIZ_7.0',
 'DMDHHSZA_1.0',
 'DMDHHSZA_2.0',
 'DMDHHSZA_3.0',
 'DMDHHSZB_1.0',
 'DMDHHSZB_2.0',
 'DMDHHSZB_3.0',
 'DMDHHSZB_4.0',
 'DMDHHSZE_1.0',
 'DMDHHSZE_2.0',
 'DMDHHSZE_3.0',
 'DMDHRGND_2.0',
 'DMDHREDU_2.0',
 'DMDHREDU_3.0',
 'DMDHREDU_4.0',
 'DMDHREDU_5.0',
 'DMDHRMAR_2.0',
 'DMDHRMAR_3.0',
 'DMDHRMAR_4.0',
 'DMDHRMAR_5.0',
 'DMDHRMAR_6.0',
 'INDFMIN2_2.0',
 'INDFMIN2_3.0',
 'INDFMIN2_4.0',
 'INDFMIN2_5.0',
 'INDFMIN2_6.0',
 'INDFMIN2_7.0',
 'INDFMIN2_8.0',
 'INDFMIN2_9.0',
 'INDFMIN2_10.0',
 'INDFMIN2_12.0',
 'INDFMIN2_13.0',
 'INDFMIN2_14.0',
 'INDFMIN2_15.0',
 'DBD895',
 'DBD905',
 'DBD910',
 'DBQ700_2.0',
 'DBQ700_3.0',
 'DBQ700_4.0',
 'DBQ700_5.0',
 'DBQ197_1.0',
 'DBQ197_2.0',
 'DBQ197_3.0',
 'DBQ197_4.0',
 'DLQ050_1.0',
 'HIQ011_1.0',
 'SMD460_1.0',
 'SMD460_2.0',
 'SMD460_3.0',
 'SMD470_1.0',
 'SMD470_2.0',
 'SMD470_3.0',
 'INQ132_1.0',
 'INQ320_2.0',
 'INQ320_3.0',
 'INQ320_4.0',
 'INQ320_5.0',
 'INQ320_6.0',
 'INQ320_7.0',
 'INQ320_8.0',
 'INQ320_9.0',
 'MCQ010_1.0',
 'MCQ080_1.0',
 'MCQ220_1.0',
 'DPQ030_1.0',
 'DPQ030_2.0',
 'DPQ030_3.0',
 'DPQ040_1.0',
 'DPQ040_2.0',
 'DPQ040_3.0',
 'DPQ050_1.0',
 'DPQ050_2.0',
 'DPQ050_3.0',
 'PAQ640',
 'PAD645',
 'PAQ655',
 'PAD660',
 'PAQ670',
 'PAD675',
 'PAD680',
 'PAQ635_1.0',
 'PAQ635_95.0',
 'PAQ650_1.0',
 'PAQ665_1.0',
 'PAQ710_1.0',
 'PAQ710_2.0',
 'PAQ710_3.0',
 'PAQ710_4.0',
 'PAQ710_5.0',
 'PAQ710_8.0',
 'PAQ715_1.0',
 'PAQ715_2.0',
 'PAQ715_3.0',
 'PAQ715_4.0',
 'PAQ715_5.0',
 'PAQ715_8.0',
 'SLQ310',
 'SLD012',
 'SLQ030_1.0',
 'SLQ030_2.0',
 'SLQ030_3.0',
 'SLQ030_9.0',
 'SLQ120_1.0',
 'SLQ120_2.0',
 'SLQ120_3.0',
 'SLQ120_4.0',
 'SMQ040_2.0',
 'SMQ040_3.0',
 'SMQ020_1.0',
 'WHD050',
 'WHD140',
 'WHQ150',
 'WHQ225_2.0',
 'WHQ225_3.0',
 'WHQ225_4.0',
 'WHQ225_5.0',
 'WHQ030_2.0',
 'WHQ030_3.0',
 'CBD071',
 'CBD111',
 'CBD121',
 'CBD131']

In [17]:
master_df = master_df[new_order]

In [18]:
master_df.head()

,Target,Age,Sex_Female,Weight (kg),Standing Height (cm),BMI,Waist Circumference (cm),Calories,Protein (gm),Carbohydrates (gm),...,WHQ225_2.0,WHQ225_3.0,WHQ225_4.0,WHQ225_5.0,WHQ030_2.0,WHQ030_3.0,CBD071,CBD111,CBD121,CBD131
0,1.0,62.0,0,94.8,184.5,27.8,101.1,2262.5,104.815,237.465,...,1,0,0,0,0,1,300.0,0.0,125.0,0.0
1,3.0,53.0,0,90.4,171.4,30.8,107.9,3467.5,114.110,290.210,...,0,0,0,1,0,0,200.0,50.0,40.0,0.0
2,1.0,78.0,0,83.4,170.1,28.8,116.5,2205.0,105.140,249.350,...,0,0,0,0,0,1,400.0,0.0,0.0,0.0
3,2.0,56.0,1,109.8,160.9,42.4,110.1,1340.0,70.380,157.990,...,1,0,0,0,0,0,300.0,250.0,50.0,0.0
4,3.0,42.0,1,55.2,164.9,20.3,80.4,853.0,25.295,111.065,...,0,0,0,1,1,0,300.0,0.0,200.0,0.0

In [20]:
master_df = master_df.rename(columns={'WHQ225_2.0': 'Time Lost 10+ lb (3-5)', 
                                      'WHQ225_3.0': 'Time Lost 10+ lb (6-10)',
                                      'WHQ225_4.0': 'Time Lost 10+ lb (11+)', 
                                      'WHQ225_5.0': 'Time Lost 10+ lb (never)',
                                      'WHQ030_2.0': 'How do you consider your weight (under)', 
                                      'WHQ030_3.0': 'How do you consider your weight (normal)',
                                      'CBD071': 'Money Spent at Grocery Store',
                                      'CBD111': 'Money Spent at Other Food Store', 
                                      'CBD121': 'Money Spent on Eating Out',
                                      'CBD131': 'Money Spent on Takeout/Delivery',
                                      'Vit A, RAE (mcg)': 'Vit A RAE (mcg)'})

In [21]:
print ('   ' + str(master_df.shape[0]) + ' rows')
print ('    ' + str(master_df.shape[1]) + ' columns')
print (str(master_df.shape[0]*master_df.shape[1]) + ' data points')
master_df.head(20)

   5266 rows
    234 columns
1232244 data points

,Target,Age,Sex_Female,Weight (kg),Standing Height (cm),BMI,Waist Circumference (cm),Calories,Protein (gm),Carbohydrates (gm),...,Time Lost 10+ lb (3-5),Time Lost 10+ lb (6-10),Time Lost 10+ lb (11+),Time Lost 10+ lb (never),How do you consider your weight (under),How do you consider your weight (normal),Money Spent at Grocery Store,Money Spent at Other Food Store,Money Spent on Eating Out,Money Spent on Takeout/Delivery
0,1.0,62.0,0,94.8,184.5,27.8,101.1,2262.5,104.815,237.465,...,1,0,0,0,0,1,300.0,0.0,125.0,0.0
1,3.0,53.0,0,90.4,171.4,30.8,107.9,3467.5,114.110,290.210,...,0,0,0,1,0,0,200.0,50.0,40.0,0.0
2,1.0,78.0,0,83.4,170.1,28.8,116.5,2205.0,105.140,249.350,...,0,0,0,0,0,1,400.0,0.0,0.0,0.0
3,2.0,56.0,1,109.8,160.9,42.4,110.1,1340.0,70.380,157.990,...,1,0,0,0,0,0,300.0,250.0,50.0,0.0
4,3.0,42.0,1,55.2,164.9,20.3,80.4,853.0,25.295,111.065,...,0,0,0,1,1,0,300.0,0.0,200.0,0.0
5,3.0,72.0,1,64.4,150.0,28.6,92.9,983.5,52.910,127.100,...,0,0,0,0,0,0,180.0,270.0,300.0,0.0
6,3.0,22.0,0,76.6,165.4,28.0,86.6,1771.0,70.020,231.555,...,0,0,1,0,0,1,0.0,500.0,100.0,0.0
7,3.0,32.0,1,64.5,151.3,28.2,93.3,2034.5,61.620,272.310,...,0,0,0,0,0,1,857.0,0.0,50.0,0.0
9,1.0,56.0,0,108.3,179.4,33.6,116.0,745.5,36.020,76.815,...,0,0,0,1,0,1,100.0,385.0,257.0,107.0
10,2.0,46.0,0,86.2,176.7,27.6,104.3,1528.5,79.215,149.395,...,0,0,0,0,0,0,200.0,0.0,0.0,28.0
11,3.0,45.0,0,76.2,177.8,24.1,90.1,3983.0,125.180,492.200,...,0,0,0,0,0,1,257.0,0.0,30.0,30.0
12,3.0,30.0,1,71.2,163.6,26.6,90.7,3113.5,89.150,394.745,...,1,0,0,0,0,0,300.0,100.0,300.0,300.0
13,2.0,67.0,1,117.8,164.1,43.7,123.0,1991.0,56.640,265.475,...,0,0,0,0,0,0,600.0,100.0,200.0,0.0
14,1.0,67.0,0,97.4,183.8,28.8,106.3,2518.5,81.160,348.155,...,0,0,0,0,0,1,200.0,20.0,60.0,40.0
15,1.0,57.0,1,80.5,150.8,35.4,113.5,1167.0,39.895,155.430,...,0,0,0,0,0,1,400.0,50.0,50.0,0.0
16,2.0,19.0,1,100.8,175.4,32.8,104.6,3463.0,114.920,395.105,...,0,1,0,0,0,0,450.0,200.0,100.0,60.0
17,3.0,24.0,1,61.8,156.4,25.3,79.5,1720.5,79.460,193.205,...,0,0,0,1,0,1,171.0,171.0,171.0,342.0
18,2.0,27.0,1,107.9,168.5,38.0,114.8,1337.0,47.870,148.540,...,0,0,0,0,0,0,300.0,300.0,100.0,150.0
19,3.0,54.0,1,59.0,149.9,26.3,88.9,1648.5,81.915,204.375,...,0,0,0,1,0,1,400.0,60.0,942.0,125.0
20,3.0,49.0,0,72.8,170.7,25.0,96.6,1376.0,49.055,191.615,...,0,0,0,1,0,1,857.0,428.0,128.0,0.0

In [62]:
master_df.to_csv('Master.csv')

In [ ]:
master_df 
avg_nutrition_df 
access_to_care_df
ages_df
blood_pressure_df
blpr_chol_df
body_measures_df
demographics_df
diet_behavior_df
disabilities_df
health_insurance_df
household_smoking_df
income_df
medical_conditions_df
mental_health_df
physical_activities_df
sleep_df
smoking_df
weight_history_df
target_df
food_location_df

##### Count up nans in a column
df['Column_Name'].isnull().sum(axis = 0)

##### Fill all NaN values in a column with a particular value
Demographics_df['DMDCITZN'].fillna(2.0, inplace=True)

##### Combining Dataframes
Full_Days_Nutrition_df = pd.merge(Day_1_Nutrition_df, Day_2_Nutrition_df, on="SEQN")
Full_Days_Nutrition_df.head()

##### Find rows that are all NaN
nan = df[df.isnull().all(axis=1)].index
nan

##### Change all '99' in a column to 1
Demographics_df.loc[Demographics_df['DMDBORN4'] == 99, 'DMDBORN4'] = 1

##### Check for Nans
df.isnull().values.any()

##### Getting Dummies
Finished_Demographics_df = pd.get_dummies(Demographics_df, columns = need_dummies, drop_first = True)

##### Rename Columns
df = df.rename(columns={'oldName1': 'newName1', 'oldName2': 'newName2'})

##### Add 'Age', then drop all 0-17 year olds
Blood_Pressure_df = pd.merge(Blood_Pressure_df, Age_df, on="SEQN")
Blood_Pressure_df = Blood_Pressure_df.drop(Blood_Pressure_df[Blood_Pressure_df.Age < 18].index)
Blood_Pressure_df.head()

##### Fill NaNs based on the median of the column
df['Col'] = df['Col'].fillna(df['Col'].median())

##### Change all values in a df that meet a condition
in this case, change them all to NaN
df[df > 9000] = np.NaN

##### For a single column
df['Col'].values[df['Col'].values > 9000] = np.NaN

##### Remove a row based on value
df = df[df.line_race != 0]